### ISSUE TITLE
Error: Requested entity was not found.

### ISSUE THREAD

**Issue by tinaroh** [rahafoundation/raha-api#133]
https://console.cloud.google.com/errors/CIXX_fqkqcyC0gE?time=P30D&project=raha-5395e

New error in prod, @rahulgi  can you take a first pass?

```
{ Error: Requested entity was not found.
    at FirebaseMessagingError.FirebaseError [as constructor] (/app/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (/app/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseMessagingError (/app/node_modules/firebase-admin/lib/utils/error.js:241:16)
    at Function.FirebaseMessagingError.fromServerError (/app/node_modules/firebase-admin/lib/utils/error.js:271:16)
    at /app/node_modules/firebase-admin/lib/messaging/messaging-api-request.js:149:50
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by rahulgi** [comment]
Appears to have come from Firebase Cloud Messaging, and it's the expected error when the device for a token cannot be found, such as if the app was uninstalled. If it's possible, we should try to unregister the device token from the client side upon app uninstall. We can also remove the token from the FCMTokens collection upon receiving this error on the server side.

However, not an urgent fix, given that notification errors shouldn't cause API endpoints to return errors.

**Comment by tinaroh** [comment]
Thanks for the investigation! Sounds like we can close for now.
